# Generated by Django 4.1.3 on 2023-01-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_isadmin_user_issupervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_Admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isSupervisor',
            new_name='is_Supervisor',
        ),
    ]
