# Generated by Django 4.1.3 on 2023-01-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_isadmin_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Admin',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Supervisor',
            new_name='isSupervisor',
        ),
    ]
